language: python

python:
  - "2.7"
  - "3.5"

services:
  - postgresql

addons:
  - postgresql: "9.6"

env:
  global:
    - DATABASE_URL=postgres://user_name:user_password@localhost:5432/fpd_db
    - ALLOWED_HOSTS="*"

install: "pip install -r requirements.txt coverage"

before_script:
  - psql -c "CREATE DATABASE fpd_db;" -U postgres
  - psql -c "CREATE USER user_name WITH PASSWORD 'user_password' CREATEDB;" -U postgres

script: coverage run manage.py test

after_success: bash <(curl -s https://codecov.io/bash)